"""202604181000 Create Counterparty_Type and Counterparty

Revision ID: a5b68d5e699d
Revises: 522a46467d43
Create Date: 2026-04-18 09:43:04.018887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5b68d5e699d'
down_revision: Union[str, Sequence[str], None] = '522a46467d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_counterparty_type',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('external_uid', sa.String(length=255), nullable=True),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.Column('created_user_id', sa.String(length=36), nullable=False),
    sa.Column('modified_datetime', sa.DateTime(), nullable=False),
    sa.Column('modified_user_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('external_uid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('_counterparty',
    sa.Column('counterparty_type_uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=255), nullable=True),
    sa.Column('registration_country', sa.String(length=2), nullable=True),
    sa.Column('address', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('external_uid', sa.String(length=255), nullable=True),
    sa.Column('parent_counterparty_uid', sa.String(length=36), nullable=True),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.Column('created_user_id', sa.String(length=36), nullable=False),
    sa.Column('modified_datetime', sa.DateTime(), nullable=False),
    sa.Column('modified_user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_type_uid'], ['_counterparty_type.uid'], ),
    sa.ForeignKeyConstraint(['parent_counterparty_uid'], ['_counterparty.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('external_uid'),
    sa.UniqueConstraint('registration_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_counterparty')
    op.drop_table('_counterparty_type')
    # ### end Alembic commands ###
