"""202604101600 Create User_Type and User

Revision ID: b93b196539f5
Revises: 
Create Date: 2026-04-10 16:34:41.091785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b93b196539f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_user_type',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.Column('created_user_id', sa.String(length=36), nullable=False),
    sa.Column('modified_datetime', sa.DateTime(), nullable=False),
    sa.Column('modified_user_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('_user',
    sa.Column('user_type_uid', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.Column('created_user_id', sa.String(length=36), nullable=False),
    sa.Column('modified_datetime', sa.DateTime(), nullable=False),
    sa.Column('modified_user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_type_uid'], ['_user_type.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_user')
    op.drop_table('_user_type')
    # ### end Alembic commands ###
